apiVersion: v1
kind: Pod
metadata:
  labels:
    repository: plessme-backend
spec:
  serviceAccountName: jenkins-sa
  containers:
  - name: buildpipeline
    image: jcr.bongladesch.com/docker/stack/buildpipeline:0.7.0
    imagePullPolicy: Always
    command:
    - cat
    tty: true
  - name: newman
    image: postman/newman:5.0.0-ubuntu
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
