apiVersion: v1
kind: Pod
metadata:
  labels:
    repository: plessme
spec:
  serviceAccountName: jenkins-sa
  containers:
  - name: buildpipeline
    image: jcr.bongladesch.com/docker/stack/buildpipeline:0.3.0
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
