apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: plessme
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: ingress-nginx-svc.kube-system.svc.bongladesch.com/docker-dev/plessme/backend
    context: .
    kaniko:
      dockerfile: src/main/docker/Dockerfile
      skipTLS: True
  cluster:
    namespace: build
    pullSecretName: regcred-dev
test:
  - image: ingress-nginx-svc.kube-system.svc.bongladesch.com/docker-dev/plessme/backend
    structureTests:
      - src/test/docker/*
deploy:
  kustomize:
    paths: ["src/main/kustomize/develop"]
