apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: plessme
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: ingress-nginx-svc.kube-system.svc.bongladesch.com/docker-dev/plessme/backend
    context: .
    kaniko:
      dockerfile: src/main/docker/Dockerfile
      skipTLS: True
  - image: ingress-nginx-svc.kube-system.svc.bongladesch.com/docker-dev/plessme/backend-docs
    context: .
    kaniko:
      dockerfile: src/main/docker/Dockerfile.docs
      skipTLS: True
  cluster:
    namespace: build
    pullSecretName: regcred-dev
deploy:
  kustomize:
    paths: ["src/main/kustomize/develop"]
