apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo:4.2.5-bionic
        name: mongo
        resources:
          limits:
            cpu: "1"
            memory: 2048Mi
          requests:
            cpu: "0.1"
            memory: 512Mi
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        livenessProbe:
          exec:
            command:
            - pgrep
            - mongod
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        envFrom:
        - secretRef:
            name: mongo-secret
        ports:
        - name: http
          containerPort: 27017
