apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: plessme-backend
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: jcr.bongladesch.com/docker-dev/plessme/backend-dev
    context: .
    docker:
      dockerfile: src/main/docker/Dockerfile.dev
    sync:
      infer:
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle.properties'
      - 'src/**/*.java'
      - 'src/**/*.properties'
deploy:
  kustomize:
    paths: ["src/main/kustomize/dev"]
