apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:12.2
        name: postgres
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: "0.1"
            memory: 256Mi
        envFrom:
        - configMapRef:
            name: postgres-cm
        - secretRef:
            name: postgres-secret
        ports:
        - name: jdbc
          containerPort: 5432
