version: '3'
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:9.0.3
    ports:
      - "8082:8080"
    volumes:
      - ./keycloak/:/tmp/
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_IMPORT: "/tmp/plessme-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
  postgres:
    container_name: postgres
    image: postgres:12.2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
