version: '3'
services:
  keycloak:
    container_name: plessme-keycloak
    image: jboss/keycloak:9.0.2
    ports:
      - "8082:8080"
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      KEYCLOAK_IMPORT: "/tmp/kc/plessme-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
    volumes:
      - ${PWD}/src/main/kustomize/base/keycloak/plessme-realm.json:/tmp/kc/plessme-realm.json
  mongo:
    container_name: plessme-mongo
    image: mongo:4.2.5-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
