version: '3'
services:
  keycloak:
    container_name: plessme-keycloak
    image: jboss/keycloak:12.0.3
    ports:
      - "8082:8080"
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      KEYCLOAK_IMPORT: "/tmp/kc/plessme-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
    volumes:
      - ${PWD}/src/main/resources/plessme-realm.json:/tmp/kc/plessme-realm.json
  mongo:
    container_name: plessme-mongo
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54.0
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    ports:
      - "8081:8081"
