version: '3'
services:
  keycloak:
    container_name: plessme-keycloak
    image: jboss/keycloak:9.0.2
    ports:
      - "8082:8080"
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
  mongo:
    container_name: plessme-mongo
    image: mongo:4.2.5-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
  # backend:
  #   container_name: plessme-backend
  #   image: jcr.bongladesch.com/docker/plessme/backend:dev
  #   build: .
  #   ports:
  #     - "8080:8080"
