apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-express
  name: mongo-express-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - image: mongo-express:0.54.0
        name: mongo-express
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: "0.1"
            memory: 256Mi
        envFrom:
        - configMapRef:
            name: mongo-express-cm
        - secretRef:
            name: mongo-express-secret
        ports:
        - name: http
          containerPort: 8081
