apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docs
  name: docs-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: backend-docs
        image: jcr.bongladesch.com/docker/plessme/backend-docs:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            protocol: TCP
            containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.1"
            memory: 128Mi
