apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name: keycloak-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - image: jboss/keycloak:9.0.2
        name: keycloak
        resources:
          limits:
            cpu: "2"
            memory: 2048Mi
          requests:
            cpu: "0.1"
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /auth/realms/plessme
            port: http
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /auth/realms/plessme
            port: http
          initialDelaySeconds: 80
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        envFrom:
        - configMapRef:
            name: keycloak-cm
        - secretRef:
            name: keycloak-secret
        volumeMounts:
        - name: keycloak-realm
          mountPath: /tmp/plessme-realm.json
          subPath: plessme-realm.json
        ports:
        - name: http
          containerPort: 8080
      volumes:
        - name: keycloak-realm
          configMap:
            name: keycloak-realm-cm
