apiVersion: v1
kind: Service
metadata:
  name: backend-debug-svc
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: debug
      protocol: TCP
      port: 5005
      targetPort: 5005
      nodePort: 30000
